### ISSUE TITLE
AMIInfoFunction - CREATE_FAILED

### ISSUE THREAD

**Issue by slwhitman** [aws-samples/amazon-cloudfront-waf-secretsmanager#4]
AMI needs to be updated to python3.9 in CloudFormation Template

<html>
<body>

AMIInfoFunction | CREATE_FAILED | Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: bc6fd4aa-0dd1-4ea2-9242-76d4f0fb323e)" (RequestToken: 123cf4a1-1802-2814-db2d-a7d59a5ba8d1, HandlerErrorCode: InvalidRequest)
-- | -- | --

</body>
</html>

**Comment by cgulliver** [comment]
Updated for Python 3.9
